<?php $__env->startSection('title', 'Visão do mercado'); ?>
<?php $__env->startSection('eyebrow', 'Visão do mercado'); ?>
<?php $__env->startSection('content'); ?>
<div class="page-heading"><div><span class="eyebrow">SEU RADAR DE PREÇOS</span><h1>Visão do mercado<span class="accent-dot">.</span></h1><p>Acompanhe o que importa. Configure o seu próximo alvo.</p></div><form method="POST" action="<?php echo e(route('assets.sync')); ?>" data-busy-form data-sync-form><?php echo csrf_field(); ?><button class="btn btn-primary" type="submit" data-busy-label="Sincronizando…" <?php if(!$canSync): echo 'disabled'; endif; ?>><?php echo $__env->make('partials.icon', ['name' => 'refresh'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <span>Sincronizar cotações</span></button></form></div>
<?php if (! ($canSync)): ?><div class="notice notice-info" role="status"><?php echo $__env->make('partials.icon', ['name' => 'info'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> A sincronização ficará disponível quando o comando de atualização estiver configurado.</div><?php endif; ?>
<div class="market-overview">
    <div class="overview-card"><span class="overview-icon"><?php echo $__env->make('partials.icon', ['name' => 'grid'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><span class="small-label">ATIVOS NA VISÃO</span><strong><?php echo e($assets->count()); ?><small>ativos</small></strong><span class="overview-caption">Moedas e criptomoedas</span></div>
    <div class="overview-card"><span class="overview-icon positive"><?php echo $__env->make('partials.icon', ['name' => 'up'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><span class="small-label">MAIOR VARIAÇÃO</span><strong class="<?php echo e($topGainer && $topGainer->variation_24h < 0 ? 'negative' : 'positive'); ?>"><?php echo e($topGainer ? number_format((float) $topGainer->variation_24h, 2, ',', '.').'%' : '—'); ?></strong><span class="overview-caption"><?php echo e($topGainer?->name ?? 'Aguardando a primeira coleta'); ?></span></div>
    <div class="overview-card"><span class="overview-icon"><?php echo $__env->make('partials.icon', ['name' => 'down'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><span class="small-label">MENOR VARIAÇÃO</span><strong class="<?php echo e($topLoser && $topLoser->variation_24h < 0 ? 'negative' : 'positive'); ?>"><?php echo e($topLoser ? number_format((float) $topLoser->variation_24h, 2, ',', '.').'%' : '—'); ?></strong><span class="overview-caption"><?php echo e($topLoser?->name ?? 'Aguardando a primeira coleta'); ?></span></div>
    <a href="<?php echo e(route('alerts.index')); ?>" class="overview-card overview-link"><span class="overview-icon accent"><?php echo $__env->make('partials.icon', ['name' => 'bell'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><span class="small-label">MEUS ALERTAS ATIVOS</span><strong><?php echo e($activeAlertsCount); ?><small>alertas</small></strong><span class="overview-caption">Gerenciar meus alertas <?php echo $__env->make('partials.icon', ['name' => 'arrow'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span></a>
</div>
<section class="market-section" data-market>
    <div class="section-heading"><div><h2>Ativos monitorados</h2><p class="freshness"><?php echo $__env->make('partials.icon', ['name' => 'clock'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> Última coleta: <?php echo e($lastFetchedAt ? \Illuminate\Support\Carbon::parse($lastFetchedAt)->timezone('America/Sao_Paulo')->format('d/m/Y H:i:s') : 'Nenhuma coleta realizada'); ?></p></div><div class="view-switch" role="group" aria-label="Visualização dos ativos"><button type="button" class="icon-button is-active" data-view="grid" aria-pressed="true" aria-label="Visualização em cartões"><?php echo $__env->make('partials.icon', ['name' => 'grid'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></button><button type="button" class="icon-button" data-view="list" aria-pressed="false" aria-label="Visualização em lista"><?php echo $__env->make('partials.icon', ['name' => 'list'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></button></div></div>
    <form class="market-toolbar" method="GET" action="<?php echo e(route('assets.index')); ?>" data-market-filters><div class="search-field"><?php echo $__env->make('partials.icon', ['name' => 'search'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><label class="visually-hidden" for="search">Pesquisar por nome ou código</label><input id="search" name="search" type="search" value="<?php echo e(request('search')); ?>" maxlength="100" placeholder="Pesquisar ativo ou código…" data-market-search><kbd>/</kbd></div><label class="visually-hidden" for="type">Tipo de ativo</label><select name="type" id="type" class="form-select filter-select" data-market-type><option value="">Todos os tipos</option><option value="fiat" <?php if(request('type') === 'fiat'): echo 'selected'; endif; ?>>Moedas</option><option value="crypto" <?php if(request('type') === 'crypto'): echo 'selected'; endif; ?>>Criptomoedas</option></select><label class="visually-hidden" for="sort">Ordenar ativos</label><select id="sort" class="form-select filter-select" data-market-sort><option value="name">Nome A–Z</option><option value="variation">Maior variação</option><option value="price">Maior preço</option></select><button type="button" class="btn btn-secondary favorites-filter" data-favorites-only aria-pressed="false"><?php echo $__env->make('partials.icon', ['name' => 'star'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> Favoritos</button><button class="btn btn-secondary" type="submit">Aplicar</button><a class="toolbar-reset" href="<?php echo e(route('assets.index')); ?>">Limpar</a></form>
    <div class="result-line"><span data-market-count aria-live="polite"><?php echo e($assets->count()); ?> ativos nesta visão</span><span>Preço de compra · Variação em 24h</span></div>
    <div class="asset-grid" data-asset-grid><?php $__currentLoopData = $assets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $asset): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php echo $__env->make('partials.asset-card', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
    <div class="empty-panel" data-market-empty <?php if($assets->isNotEmpty()): ?> hidden <?php endif; ?>><span class="empty-icon"><?php echo $__env->make('partials.icon', ['name' => 'search'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><h3>Nenhum ativo nesta visão</h3><p>Ajuste a busca ou os filtros para encontrar o que você procura.</p><a href="<?php echo e(route('assets.index')); ?>" class="btn btn-secondary">Ver todos os ativos</a></div>
</section>
<section class="callout-banner"><span class="callout-icon"><?php echo $__env->make('partials.icon', ['name' => 'bell'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><div><h2>Um preço alvo. Um aviso na hora certa.</h2><p>Configure o valor e a condição. Seu alerta será verificado a cada sincronização.</p></div><a href="<?php echo e(route('alerts.create')); ?>" class="btn btn-secondary">Criar meu alerta <?php echo $__env->make('partials.icon', ['name' => 'arrow'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></a></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\RES0147476\Documents\Moedas\monitor-cotacoes-laravel\resources\views/assets/index.blade.php ENDPATH**/ ?>